export const panels = [
    {
        id: 1,
        image:
            'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1920&q=80',
        title: 'THE ART OF STYLE',
        subtitle: 'Where fashion meets expression',
        category: 'FASHION',
        author: 'Elena Vogt',
        issue: '01',
        layout: 'center',
        overlay: 'from-black/50 via-black/20 to-transparent',
        accent: 'text-amber-200',
    },
    {
        id: 2,
        image:
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1920&q=80',
        title: 'WILD & FREE',
        subtitle: 'A journey into the untamed',
        category: 'NATURE',
        author: 'Marcus Reed',
        issue: '02',
        layout: 'bottom-left',
        overlay: 'from-black/60 via-black/30 to-transparent',
        accent: 'text-emerald-200',
    },
    {
        id: 3,
        image:
            'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=1920&q=80',
        title: 'CONCRETE DREAMS',
        subtitle: 'The poetry of urban geometry',
        category: 'ARCHITECTURE',
        author: 'Sofia Chen',
        issue: '03',
        layout: 'right',
        overlay: 'from-black/40 via-black/50 to-black/70',
        accent: 'text-sky-200',
    },
    {
        id: 4,
        image:
            'https://plus.unsplash.com/premium_photo-1664547606209-fb31ec979c85?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        title: 'THE OPEN ROAD',
        subtitle: 'Wanderlust and the horizon',
        category: 'TRAVEL',
        author: 'James Kariuki',
        issue: '04',
        layout: 'center-bottom',
        overlay: 'from-black/30 via-black/50 to-black/80',
        accent: 'text-orange-200',
    },
    {
        id: 5,
        image:
            'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1920&q=80',
        title: 'COLOR THEORY',
        subtitle: 'The language of visual emotion',
        category: 'ART',
        author: 'Nina Kraviz',
        issue: '05',
        layout: 'left',
        overlay: 'from-black/60 via-black/30 to-transparent',
        accent: 'text-rose-200',
    },
    {
        id: 6,
        image:
            'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1920&q=80',
        title: 'MODERN LIVING',
        subtitle: 'Designing the future home',
        category: 'CULTURE',
        author: 'David Park',
        issue: '06',
        layout: 'bottom-right',
        overlay: 'from-black/30 via-black/50 to-black/80',
        accent: 'text-yellow-200',
    },
];
